# Generated by Django 4.0.5 on 2022-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_categories_city_subcategories_seller_product_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='account_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
